times = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG', 'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará', 'Atlético-GO', 'Avaí', 'Juventude')
print('=-' *30)
print(f'Times do Brasileirão 2022: {times}')
print('=-' *30)
print(f'5 primeiros colocados: {times[0:6]}')
print('=-' *30)
print(f'4 últimos colocados: {times[16:20]}')
print('=-' *30)
print(f'Times do Brasileirão em ordem alfabética: {sorted(times)}')
print('=-' *30)
print(f'Posição do Avaí: {(times.index("Avaí")) + 1}°')
print('=-' *30)