#print('='*20)
#print('Oi'*5)
#print('='*20)

nome = input('Qual é o seu nome?')
print(f'Prazer em te conhecer {nome :20}!')
print(f'Prazer em te conhecer {nome :>20}!')
print(f'Prazer em te conhecer {nome :<20}!')
print(f'Prazer em te conhecer {nome :^20}!')
print(f'Prazer em te conhecer {nome :=^20}!')
